INSERT INTO stat(name, short) VALUES('Strength', 'STR');
INSERT INTO stat(name, short) VALUES('Dexterity', 'DEX');
INSERT INTO stat(name, short) VALUES('Constitution', 'CON');
INSERT INTO stat(name, short) VALUES('Intelligence', 'INT');
INSERT INTO stat(name, short) VALUES('Wisdom', 'WIS');
INSERT INTO stat(name, short) VALUES('Charisma', 'CHA');

INSERT INTO stat_type(name, short) VALUES('Main', 'm');
INSERT INTO stat_type(name, short) VALUES('Sub', 's');

INSERT INTO ability(name, def, cd) VALUES ('Slash', 'Deal [STR Base] physical damage to a single target.', 1);
INSERT INTO ability(name, def, cd) VALUES ('Guard', 'Negate [CON Base] Physical damage taken for 1 round.', 1);
INSERT INTO ability(name, def, cd) VALUES ('Concentrate', 'Gain +1 physical damage bonus for 6 rounds.', 6);
INSERT INTO ability(name, def, cd) VALUES ('Rage', 'Gain [Rage] for 2 rounds.', 1);
INSERT INTO ability(name, def, cd) VALUES ('Axe Throw', 'Deal [STR base] physical damage to a single target.', 1);
INSERT INTO ability(name, def, cd) VALUES ('Axe Swing', 'Deal [STR base] physical to all enemies.', 4);
INSERT INTO ability(name, def, cd) VALUES('Jab', 'Deal [STR base] Physical damage, inflict [Hel seal].', 1);
INSERT INTO ability(name, def, cd) VALUES('Ignition', 'On a single enemy convert [Hel seal] to [Burn] for 3 rounds.', 1);
INSERT INTO ability(name, def, cd) VALUES('Combust', 'On a single enemy, consume [Hel seal] to deal [INT base] necrotic damage.', 5);
INSERT INTO ability(name, def, cd) VALUES('Slam', 'Deal [CON base] physical damage to a single enemy.', 1);
INSERT INTO ability(name, def, cd) VALUES('Organic Skin', 'Gain [Defense] for 3 rounds.', 3);
INSERT INTO ability(name, def, cd) VALUES('Latch', 'Inflict [Latch] on an enemy or ally.', 5);
INSERT INTO ability(name, def, cd, mp_cost) VALUES('Plant Heal', 'Heal [WIS base] to a single ally.', 1, 1);
INSERT INTO ability(name, def, cd, mp_cost) VALUES('Overgrowth', '[Stun] a single enemy.', 1, 1);
INSERT INTO ability(name, def, cd, mp_cost) VALUES('Familiar', 'Summon a [Familiar]', 1, 1);
INSERT INTO ability(name, def, cd) VALUES('Storm Totem', 'Summon [Storm totem] for 5 rounds.', 6);
INSERT INTO ability(name, def, cd) VALUES('Tempest Shift', 'Apply [Slow] on all enemies for 1 round.', 1);
INSERT INTO ability(name, def, cd) VALUES('Rain', 'Deal [WIS base] magic damage to all enemies.', 2);
INSERT INTO ability(name, def, cd) VALUES('Fast Forward', 'Grant a single ally [WIS base] mana.', 1);
INSERT INTO ability(name, def, cd, mp_cost) VALUES('Rewind', 'Rewind a single target to the previous round health value.', 2, 3);
INSERT INTO ability(name, def, cd, mp_cost) VALUES('Pause', '[Stun] a single enemy for 1 round.', 1, 3);
INSERT INTO ability(name, def, cd) VALUES('Natural Protection', 'Grant an ally [Defense] for 1 round.', 1);
INSERT INTO ability(name, def, cd, mp_cost) VALUES('Spiritual Protection', 'Grant an ally [Defense+] for 3 rounds.', 4, 2);
INSERT INTO ability(name, def, cd, mp_cost) VALUES('Warding Light', 'Remove [Invisibility] for enemies, and cleans [Blindness] for allies.', 2, 2);
INSERT INTO ability(name, def, cd, mp_cost) VALUES('Undead', 'Summon an [Undead] containing half of your health.', 1, 1);
INSERT INTO ability(name, def, cd, mp_cost) VALUES('Decay', 'Channel a blood field that will deal [CHA base] Magic damage to all enemies. MP per second.', 1, 1);
INSERT INTO ability(name, def, cd, mp_cost) VALUES('Plague', 'Apply [Dark Plague] on a single target for 3 rounds.', 6, 2);
INSERT INTO ability(name, def, cd, mp_cost) VALUES('Hex', 'Apply [Hex] on a single enemy.', 1, 1);
INSERT INTO ability(name, def, cd, mp_cost) VALUES('Hex Field', 'Channel a hex field, enemies casting abilities will be inflected by [Hex]. MP per second.', 1, 1);
INSERT INTO ability(name, def, cd) VALUES('Curse Rupture', 'Detonate all [Hex] stacks on enemies to deal half [INT base] Magic damage multiplied by the amount of stacks.', 3);
INSERT INTO ability(name, def, cd, mp_cost) VALUES('Void Spawn', 'Summon a [Voidling]', 5, 1);
INSERT INTO ability(name, def, cd, mp_cost) VALUES('Void Matter', 'Replenish a summon, familiar, or construct_s HP by [CHA base]', 1, 2);
INSERT INTO ability(name, def, cd) VALUES('Guardian', 'Summon a [Void Guardian]', 10);
INSERT INTO ability(name, def, cd, mp_cost) VALUES('Harvest', 'Deal half [CHA base] necrotic damage to all enemies.', 1, 3);
INSERT INTO ability(name, def, cd, mp_cost) VALUES('Death Mark', 'Inflict [Death Mark] on a single enemy for 3 rounds.', 7, 4);
INSERT INTO ability(name, def, cd) VALUES('Underworld', 'Remove all inflictions and debuffs on the caster.', 4);
INSERT INTO ability(name, def, cd, mp_cost) VALUES('Heal', 'Heal a single ally [CHA base].', 1, 1);
INSERT INTO ability(name, def, cd, mp_cost) VALUES('Divine Connection', 'Place [Faith] on a single ally for 3 rounds.', 3, 3);
INSERT INTO ability(name, def, cd, mp_cost) VALUES('Holy Spear', 'Deal [CHA base] holy damage to a single enemy.', 1, 1);
INSERT INTO ability(name, def, cd, mp_cost) VALUES('Fortune', 'Grant a single ally [Fortune].', 1, 1);
INSERT INTO ability(name, def, cd, mp_cost) VALUES('Misfortune', 'Grant a single enemy [Misfortune].', 1, 1);
INSERT INTO ability(name, def, cd, mp_cost) VALUES('Blessing', 'Grant an ally +1 on all stats for 2 rounds.', 4, 2);
INSERT INTO ability(name, def, cd, mp_cost) VALUES('Solar Beam', 'Deal [INT base] light damage to a single enemy.', 1, 1);
INSERT INTO ability(name, def, cd, mp_cost) VALUES('Reflect', 'Inflict [Mirror] at a single target for 4 rounds.', 1, 3);
INSERT INTO ability(name, def, cd, mp_cost) VALUES('Shun', '[Stun] a single target.', 1, 1);
INSERT INTO ability(name, def, cd, mp_cost) VALUES('Surge', 'Deal [WIS base] dark damage to a single enemy.', 1, 1);
INSERT INTO ability(name, def, cd, mp_cost) VALUES('Chain Bind', '[Stun] a single enemy and another random enemy,.', 2, 3);
INSERT INTO ability(name, def, cd, mp_cost) VALUES('Ritual', '[Stun] all enemies and deal half [WIS base] dark damage.', 6, 6);
INSERT INTO ability(name, def, cd, mp_cost) VALUES('Magic Missile', 'Deal [INT Base] magical damage to a single target.', 1, 1);
INSERT INTO ability(name, def, cd, mp_cost) VALUES('Mana Flux', 'Gain [Mana Flux] for 3 rounds.', 6, 2);
INSERT INTO ability(name, def, cd) VALUES('Hyper Flux', 'Consume all MP, granting INT for each MP consumed for 2 rounds.', 3);
INSERT INTO ability(name, def, cd, mp_cost) VALUES('Pulse Fire', 'Deal [WIS base] magic damage to a single enemy.', 1, 1);
INSERT INTO ability(name, def, cd, mp_cost) VALUES('Tech Advancement', 'Grant an ally [Upgrade] for 1 round.', 3, 5);
INSERT INTO ability(name, def, cd, mp_cost) VALUES('Holo Shield', 'Grant [Magic Shield] for you or an ally for 2 rounds.', 3, 2);
INSERT INTO ability(name, def, cd, mp_cost) VALUES('Fireball', 'Deal [INT base] Fire damage.', 1, 1);
INSERT INTO ability(name, def, cd, mp_cost) VALUES('Ice Spike', 'Deal [INT base] Ice damage.', 1, 1);
INSERT INTO ability(name, def, cd, mp_cost) VALUES('Shatter', 'Deal [INT base] physical damage to all enemies.', 2, 3);
INSERT INTO ability(name, def, cd, mp_cost) VALUES('Destruction', 'Gain [Destruction].', 1, 1);
INSERT INTO ability(name, def, cd, mp_cost) VALUES('Serenity', 'Gain [Serenity].', 1, 1);
INSERT INTO ability(name, def, cd, mp_cost) VALUES('Obedience', 'Gain [Obedience].', 1, 1);
INSERT INTO ability(name, def, cd) VALUES('Arrow Shot', 'Fire an arrow to deal [DEX base] physical damage.', 1);
INSERT INTO ability(name, def, cd, mp_cost) VALUES('Arrow Infusion', 'Apply a chosen infliction on the next Arrow Shot.', 1, 2);
INSERT INTO ability(name, def, cd) VALUES('Headshot', 'Next Arrow Shot will crit.', 6);
INSERT INTO ability(name, def, cd, mp_cost) VALUES('Open Fire', 'Deal [STR base] physical damage to a single enemy.', 1, 1);
INSERT INTO ability(name, def, cd, mp_cost) VALUES('Deadeye', 'Gain 50% crit damage boost for 4 rounds.', 3, 2);
INSERT INTO ability(name, def, cd, mp_cost) VALUES('Riptide Shots', 'Deal x2 [STR base] physicam damage to a single enemy.', 3, 2);
INSERT INTO ability(name, def, cd, mp_cost) VALUES('Reshuffle', 'Reshuffle Deck Buff', 1, 1);
INSERT INTO ability(name, def, cd, mp_cost) VALUES('Card Toss', 'Deal [DEX base] physical damage to a single enemy.', 1, 1);
INSERT INTO ability(name, def, cd, mp_cost) VALUES('Quick Feet', 'Gain [Quick Feet] for 1 round.', 3, 2);
INSERT INTO ability(name, def, cd) VALUES('Shank', 'Deal [STR base] physical damage to a single target.', 1);
INSERT INTO ability(name, def, cd) VALUES('Bear Trap', '[Stun] a single target for one round.', 3);
INSERT INTO ability(name, def, cd) VALUES('Hunters Mark', 'Apply [Hunter Mark] on a single target for 3 rounds.', 3);
INSERT INTO ability(name, def, cd) VALUES('Hide', 'Become invisible for 1 round.', 1);
INSERT INTO ability(name, def, cd) VALUES('Pickpocket', 'Deal [STR base] physical damage with a chance to receive gold.', 1);
INSERT INTO ability(name, def, cd) VALUES('Execute', 'Deal [STR base] physical damage, executing enemies at or below 10% max health. Executing resets cooldown.', 8);
INSERT INTO ability(name, def, cd, mp_cost) VALUES('Fear', 'Inflict [Fear], to a single enemy for 3 rounds.', 3, 2);
INSERT INTO ability(name, def, cd, mp_cost) VALUES('Dread', 'Inflict [Nightmare Strike] to a single enemy for 2 rounds.', 1, 1);
INSERT INTO ability(name, def, cd, mp_cost) VALUES('Terror', 'Deal [STR base] physical damage, consuming all stacks of [Nightmare Strike].', 8, 4);
INSERT INTO ability(name, def, cd, mp_cost) VALUES('Fake Out', 'Summon a [Self Replica].', 3, 2);
INSERT INTO ability(name, def, cd, mp_cost) VALUES('Laughter', 'Deal half [DEX base] magic damage to all enemies.', 1, 1);
INSERT INTO ability(name, def, cd, mp_cost) VALUES('Jack in the Box', 'Inflic ta random Debuff/Infliction to all enemies.', 8, 4);
INSERT INTO ability(name, def, cd) VALUES('Melody', 'Grant a single ally +1 [STR] and +1 [INT].', 1);
INSERT INTO ability(name, def, cd, mp_cost) VALUES('Sound Wave', 'Grant all allies [Inspire] and enemies [Discourage].', 3, 2);
INSERT INTO ability(name, def, cd, mp_cost) VALUES('Reverb', 'Grant a single ally [Double Cast].', 7, 3);
INSERT INTO ability(name, def, cd) VALUES('Charm', 'Apply [Charm] to a single enemy for 2 rounds.', 2);
INSERT INTO ability(name, def, cd, mp_cost) VALUES('Submission', 'Inflict [Complete Submission] on a single target.', 1, 5);
INSERT INTO ability(name, def, cd, mp_cost) VALUES('Demand', 'Grant your familiar [Double Cast]', 6, 1);
INSERT INTO ability(name, def, cd, mp_cost) VALUES('String', 'Inflict [Strung] on a single enemy.', 1, 1);
INSERT INTO ability(name, def, cd, mp_cost) VALUES('Pull', 'Deal [CHA base] magic damage to a single enemy. May convert [Strung] to [Stun].', 1, 4);
INSERT INTO ability(name, def, cd, mp_cost) VALUES('Control', 'Inflict [Puppeted] to a single enemy for 5 rounds.', 7, 4);
INSERT INTO ability(name, def, cd, mp_cost) VALUES('High Note', 'Deal half [CHA base] magic damage to a single enemy.', 1, 2);
INSERT INTO ability(name, def, cd, mp_cost) VALUES('Minor Note', 'Grant the party [Remedy] for 3 rounds.', 4, 6);
INSERT INTO ability(name, def, cd, mp_cost) VALUES('Major Note', 'Grant the party [Legato] for 3 rounds.', 7, 9);
INSERT INTO ability(name, def, cd) VALUES('Strike1', 'Deal [STR base] physical damage to a single enemy.', 1);
INSERT INTO ability(name, def, cd) VALUES('Parry', 'Grant [Parry].', 3);
INSERT INTO ability(name, def, cd) VALUES('Defend', 'Grant [Defense] for 1 round.', 1);
INSERT INTO ability(name, def, cd) VALUES('Punch', 'Deal [STR base] physical damage, applying [Imbalance] for 1 round.', 1);
INSERT INTO ability(name, def, cd) VALUES('Kick', 'Deal [STR base] physical damage, applying [Stun] for 1 round.', 3);
INSERT INTO ability(name, def, cd) VALUES('Guard1', 'Gain [Defense] for 2 rounds.', 3);
INSERT INTO ability(name, def, cd, mp_cost) VALUES('Bonk', 'Deal half [WIS base] physical damage to a single enemy, gaining [Ki].', 1, 1);
INSERT INTO ability(name, def, cd, mp_cost) VALUES('Meditate', 'Convert [Ki] to [Regeneration].', 1, 2);
INSERT INTO ability(name, def, cd, mp_cost) VALUES('Ki Unlock', 'Convert [Ki] to [Bonk Boost].', 1, 1);
INSERT INTO ability(name, def, cd) VALUES('Orange', 'Heal [STR base] and cleanse [Poison].', 3);
INSERT INTO ability(name, def, cd) VALUES('Rally', 'Grant the party +1 STR and +1 DEX for 3 rounds.', 3);
INSERT INTO ability(name, def, cd) VALUES('Cannon', 'Summon a [Cannon].', 1);
INSERT INTO ability(name, def, cd) VALUES('Bash', 'Deal [CON base] physical damage to a single target.', 1);
INSERT INTO ability(name, def, cd) VALUES('Defensive Stance', 'Grant [Defense] for 2 rounds.', 4);
INSERT INTO ability(name, def, cd) VALUES('Slash1', 'Deal [STR base] physical damage to a single enemy.', 1);
INSERT INTO ability(name, def, cd, mp_cost) VALUES('Retribution', 'Deal half [CHA base] Strength damage to a single target.', 1, 1);
INSERT INTO ability(name, def, cd) VALUES('Redemption', 'Party gains [Regeneration] for 3 rounds.', 3);
INSERT INTO ability(name, def, cd, mp_cost) VALUES('Divine Smite', 'Deal [CHA base] holy damage to all enemies.', 4, 3);
INSERT INTO ability(name, def, cd) VALUES('Command', 'Grant target ally [Triumph] for 1 round.', 1);
INSERT INTO ability(name, def, cd) VALUES('Plunge', 'Deal 2x [STR base] physical damage to target enemy.', 2);
INSERT INTO ability(name, def, cd) VALUES('Guard Stance', 'Party gains [Defense] for 2 rounds.', 4);
INSERT INTO ability(name, def, cd, mp_cost) VALUES('Blade Surge', 'Deal half [DEX base] physical damage to target enemy.', 1, 1);
INSERT INTO ability(name, def, cd, mp_cost) VALUES('Sharp Rain', 'Deal half [DEX base] physical damage to all enemies.', 1, 2);
INSERT INTO ability(name, def, cd, mp_cost) VALUES('Dancing Blade', 'Summon a [Floating Blade]', 1, 6);
INSERT INTO ability(name, def, cd) VALUES('Lost Spell', 'Replenish all party mana by half of [WIS base].', 5);
INSERT INTO ability(name, def, cd, mp_cost) VALUES('Portal', 'Target ally gains [Warp].', 2, 3);
INSERT INTO ability(name, def, cd, mp_cost) VALUES('Quotation', 'Deal [WIS base] magic damage to a single enemy.', 1, 1);
INSERT INTO ability(name, def, cd, mp_cost) VALUES('Doorbell', 'Gain [Defense+] for 3 rounds.', 3, 5);
INSERT INTO ability(name, def, cd) VALUES('Lock', 'Disable target [Doorway].', 1);
INSERT INTO ability(name, def, cd) VALUES('Unlock', 'Enable target [Doorway].', 1);
INSERT INTO ability(name, def, cd, mp_cost) VALUES('Window Clean', 'Target ally gains [Immunity] for 2 rounds.', 6, 2);
INSERT INTO ability(name, def, cd, mp_cost) VALUES('Spray Cleaner', 'Target gains [Poison] for 2 rounds.', 2, 3);
INSERT INTO ability(name, def, cd, mp_cost) VALUES('Sweep', 'Remove all debuffs and inflictions from target ally.', 1, 1);
INSERT INTO ability(name, def, cd, mp_cost) VALUES('Notes', 'Deal [WIS base] psychic damage to a single enemy.', 1, 2);
INSERT INTO ability(name, def, cd, mp_cost) VALUES('Bird Call', 'Summon [Bird Familiar].', 6, 5);
INSERT INTO ability(name, def, cd, mp_cost) VALUES('Passage', 'Target enemy gains [Passage] for 3 rounds.', 3, 3);

INSERT INTO passive(name, def) VALUES ('Strength Buffer', '+1 STR.');
INSERT INTO passive(name, def) VALUES ('Broken Blade', 'At below 50% HP, gain +1 STR.');
INSERT INTO passive(name, def) VALUES ('Mediate', 'Taking damage with [Rage] grants a stack of [Mediate].');
INSERT INTO passive(name, def) VALUES ('Frustration', 'Increase crit damage by 50%.');
INSERT INTO passive(name, def) VALUES ('Helish Aura', 'The party becomes immune to fire damage.');
INSERT INTO passive(name, def) VALUES ('HelSpawn', 'Gain +1 CON.');
INSERT INTO passive(name, def) VALUES ('Self Regen', 'Gain permanent [Regeneration].');
INSERT INTO passive(name, def) VALUES ('Devour', 'Winning battles grants +1 CON permanently.');
INSERT INTO passive(name, def) VALUES ('Thorns', 'Casting spells inflict [Poison] on a random enemy for 2 rounds.');
INSERT INTO passive(name, def) VALUES ('Animal Tongue', 'Ability to speak to animals.');
INSERT INTO passive(name, def) VALUES ('Mending Spirit', 'Casting spells applies [Regeneration] to a random ally.');
INSERT INTO passive(name, def) VALUES ('Warding', 'Gain 1+ warding efficiency.');
INSERT INTO passive(name, def) VALUES ('Foresight', 'See enemy actions before they perform them.');
INSERT INTO passive(name, def) VALUES ('Timezone', 'Short rest is considered a long rest.');
INSERT INTO passive(name, def) VALUES ('Ward Crafter', 'Gain ward crafting proficiency.');
INSERT INTO passive(name, def) VALUES ('Clarity', 'Gain +1 WIS.');
INSERT INTO passive(name, def) VALUES ('Blood Draw', 'Dealing magic damage will heal you.');
INSERT INTO passive(name, def) VALUES ('Sacrifice', 'If you can_t spend mana to cast a spell, consume your health instaed.');
INSERT INTO passive(name, def) VALUES ('Essence Capture', 'Dealing damage will heal you.');
INSERT INTO passive(name, def) VALUES ('Witchcraft', 'Gain advantage and proficiency in spellcrafting and witch arts.');
INSERT INTO passive(name, def) VALUES ('Void Blessing', 'Grant summons, familiars, and constructs +1 Level.');
INSERT INTO passive(name, def) VALUES ('Focus Point', 'Grant 50% crit chance to summons, familiars, and constructs.');
INSERT INTO passive(name, def) VALUES ('Afterlife', 'Enemies dying will grant you +1 CON for the duration of the battle.');
INSERT INTO passive(name, def) VALUES ('Second Passing', 'Gain -3 CON. On death, ressurect with 50% max health. Refreshes every battle.');
INSERT INTO passive(name, def) VALUES ('Resurrection', 'The next ally that dies will be resurrected. Occurs once per battle.');
INSERT INTO passive(name, def) VALUES ('Prayer', 'On turn skip, grant all party members [Defense] for 1 round.');
INSERT INTO passive(name, def) VALUES ('Lucky', 'Grant yourself and your allies +1 on dice rolls.');
INSERT INTO passive(name, def) VALUES ('Absolute', 'Upon dying, deal x2 [INT base] light damage on all enemies.');
INSERT INTO passive(name, def) VALUES ('Spectrum', 'Critical hits on enemies will apply [Mirror] for 1 round.');
INSERT INTO passive(name, def) VALUES ('Devotion', 'Gain WIS for the amount of enemies inflicted with [Stun].');
INSERT INTO passive(name, def) VALUES ('Bow', 'Skipping grants you [Defense] for 1 round.');
INSERT INTO passive(name, def) VALUES ('Wisdom Buffer', 'Gain 1+ WIS.');
INSERT INTO passive(name, def) VALUES ('Continuity', 'Reduce Magic base damage intake by half.');
INSERT INTO passive(name, def) VALUES ('Magic Tinkerer', 'Gain advantage on Magic item crafting.');
INSERT INTO passive(name, def) VALUES ('Creativity', 'Gain +1 CHA.');
INSERT INTO passive(name, def) VALUES ('Tempest', 'Grant yourself and your allies +1 DEX.');
INSERT INTO passive(name, def) VALUES ('Spell Proficiency', 'Gain advantage on spellcrafting.');
INSERT INTO passive(name, def) VALUES ('Spell Memory', 'Gain +1 INT.');
INSERT INTO passive(name, def) VALUES ('Spellcraft', 'Gain advantage on spellcrafting.');
INSERT INTO passive(name, def) VALUES ('Arrow Proficiency', 'Gain x2 arrows on crafting.');
INSERT INTO passive(name, def) VALUES ('Arrow Counter', 'Successful dodges from you or an ally grants fire Arrow Shot.');
INSERT INTO passive(name, def) VALUES ('Headshot', 'Gain 25% crit chance.');
INSERT INTO passive(name, def) VALUES ('Quick Shot', '[Stun] enemies automatically casts Open Fire on them at no cost.');
INSERT INTO passive(name, def) VALUES ('Deck Buff', 'Randomly gain [Mana Card], [Flame Card], or [Heal Card].');
INSERT INTO passive(name, def) VALUES ('Loot Lucky', 'Gain advantage while collecting loot.');
INSERT INTO passive(name, def) VALUES ('Swift Feet', 'Gain advantage on dodge roles.');
INSERT INTO passive(name, def) VALUES ('Hunting Proficiency', 'Gain advantage on material scavenging.');
INSERT INTO passive(name, def) VALUES ('Lootrunner', 'Gain advantage on loot opening.');
INSERT INTO passive(name, def) VALUES ('Lockpick', 'Gain advantage on lock picking.');
INSERT INTO passive(name, def) VALUES ('Anxiety', '[Fear], [Stun], and [Slow] triggers Dread on the target.');
INSERT INTO passive(name, def) VALUES ('Shadow Step', 'Gain +1 DEX.');
INSERT INTO passive(name, def) VALUES ('Jackpot', 'Ever 3 rounds, flip a coin to receive bonuses.');
INSERT INTO passive(name, def) VALUES ('Grand Illusion', 'Party gains dodge advantage.');
INSERT INTO passive(name, def) VALUES ('Tuning', 'Increased instrument mastery.');
INSERT INTO passive(name, def) VALUES ('Natural Charm', 'Gain persuasion advantage.');
INSERT INTO passive(name, def) VALUES ('Charisma Advantage', 'Gain +1 CHA.');
INSERT INTO passive(name, def) VALUES ('Familiar Advancement', 'Grant +1 Level for familiars.');
INSERT INTO passive(name, def) VALUES ('Dexful Hands', 'Gain +1 DEX.');
INSERT INTO passive(name, def) VALUES ('Puppet Show', 'Gain +1 CHA for each enemy inflicted with [Strung].');
INSERT INTO passive(name, def) VALUES ('Show Time', 'Evert third ability used, enter [Stage Mode] for 3 rounds.');
INSERT INTO passive(name, def) VALUES ('Background Track', 'Every round, cleanse a random ally of one debuff, infliction, or crowd control.');
INSERT INTO passive(name, def) VALUES ('Strong Heart', 'Gain [String Heart].');
INSERT INTO passive(name, def) VALUES ('Honor', 'Party gains +1 STR.');
INSERT INTO passive(name, def) VALUES ('No Weapon', 'Gain +1 STR and +1 CON when weapon slot is empty.');
INSERT INTO passive(name, def) VALUES ('Inner Strength', 'Gain +1 STR.');
INSERT INTO passive(name, def) VALUES ('Ki Protection', 'Ki grants +1 CON per stack.');
INSERT INTO passive(name, def) VALUES ('Hard Body', 'Gain +1 CON.');
INSERT INTO passive(name, def) VALUES ('Crew', 'Gain +1 STR for every living party member.');
INSERT INTO passive(name, def) VALUES ('Leadership', 'Gain advantage on initiative roll.');
INSERT INTO passive(name, def) VALUES ('Survivability', 'Party gains +1 CON.');
INSERT INTO passive(name, def) VALUES ('Shield Proficiency', 'Gain Shield Level +1.');
INSERT INTO passive(name, def) VALUES ('Holy Protection', 'Gain CON equal to half of base CHA.');
INSERT INTO passive(name, def) VALUES ('Holy Spirit', 'Gain +1 CON.');
INSERT INTO passive(name, def) VALUES ('Honor1', 'Gain CON equal to half of STR.');
INSERT INTO passive(name, def) VALUES ('Vows', 'Taking damage grants [Defense] for 1 round.');
INSERT INTO passive(name, def) VALUES ('Blade Form', 'Abilities grant [Bladedancer Form] until attacked.');
INSERT INTO passive(name, def) VALUES ('Blade Stance', 'Having 2 stacks of [Floating Blade] grants [Defense+].');
INSERT INTO passive(name, def) VALUES ('Learning', 'Party gains +1 Level.');
INSERT INTO passive(name, def) VALUES ('Understanding', 'Allies gain +1 Spell Level.');
INSERT INTO passive(name, def) VALUES ('Otherworldly', 'Gain double max health.');
INSERT INTO passive(name, def) VALUES ('Doorway', 'Gain [Doorway].');
INSERT INTO passive(name, def) VALUES ('Wet Floor Sign', 'All enemies gain [Slippery].');
INSERT INTO passive(name, def) VALUES ('Clean', 'Gain immunity to inflictions and debuffs.');
INSERT INTO passive(name, def) VALUES ('Calling', 'Gain CON equal to half of WIS.');
INSERT INTO passive(name, def) VALUES ('Reply', 'Taking damage from enemies with [Passage] causes them to receive the same amount of damage.');

------------------------------------------------------------------------------------------+
-- POPULATE CLASS
------------------------------------------------------------------------------------------+

INSERT INTO class(name) VALUES('Warrior');
INSERT INTO class_stat(class_id, stat_id, type_id) VALUES(1, 1, 1);
INSERT INTO class_stat(class_id, stat_id, type_id) VALUES(1, 3, 1);
INSERT INTO class_stat(class_id, stat_id, type_id) VALUES(1, 2, 2);
INSERT INTO class_stat(class_id, stat_id, type_id) VALUES(1, 5, 2);
INSERT INTO class_ability(class_id, ability_id) VALUES (1, 1);
INSERT INTO class_ability(class_id, ability_id) VALUES (1, 2);
INSERT INTO class_ability(class_id, ability_id) VALUES (1, 3);
INSERT INTO class_passive(class_id, passive_id) VALUES (1, 1);
INSERT INTO class_passive(class_id, passive_id) VALUES (1, 2);

INSERT INTO class(name, parent_id) VALUES('Barbarian', 1);
INSERT INTO class_stat(class_id, stat_id, type_id) VALUES(2, 1, 1);
INSERT INTO class_stat(class_id, stat_id, type_id) VALUES(2, 2, 1);
INSERT INTO class_stat(class_id, stat_id, type_id) VALUES(2, 3, 2);
INSERT INTO class_ability(class_id, ability_id) VALUES (2, 4);
INSERT INTO class_ability(class_id, ability_id) VALUES (2, 5);
INSERT INTO class_ability(class_id, ability_id) VALUES (2, 6);
INSERT INTO class_passive(class_id, passive_id) VALUES (2, 3);
INSERT INTO class_passive(class_id, passive_id) VALUES (2, 4);

INSERT INTO class(name, parent_id) VALUES('Illrigger', 1);
INSERT INTO class_stat(class_id, stat_id, type_id) VALUES(3, 1, 1);
INSERT INTO class_stat(class_id, stat_id, type_id) VALUES(3, 4, 1);
INSERT INTO class_stat(class_id, stat_id, type_id) VALUES(3, 3, 2);
INSERT INTO class_ability(class_id, ability_id) VALUES (3, 7);
INSERT INTO class_ability(class_id, ability_id) VALUES (3, 8);
INSERT INTO class_ability(class_id, ability_id) VALUES (3, 9);
INSERT INTO class_passive(class_id, passive_id) VALUES (3, 5);
INSERT INTO class_passive(class_id, passive_id) VALUES (3, 6);

INSERT INTO class(name, parent_id) VALUES('Symbiote', 1);
INSERT INTO class_stat(class_id, stat_id, type_id) VALUES(4, 3, 1);
INSERT INTO class_stat(class_id, stat_id, type_id) VALUES(4, 1, 2);
INSERT INTO class_ability(class_id, ability_id) VALUES (4, 10);
INSERT INTO class_ability(class_id, ability_id) VALUES (4, 11);
INSERT INTO class_ability(class_id, ability_id) VALUES (4, 12);
INSERT INTO class_passive(class_id, passive_id) VALUES (4, 7);
INSERT INTO class_passive(class_id, passive_id) VALUES (4, 8);

INSERT INTO class(name) VALUES('Druid');
INSERT INTO class_stat(class_id, stat_id, type_id) VALUES(5, 5, 1);
INSERT INTO class_stat(class_id, stat_id, type_id) VALUES(5, 6, 2);
INSERT INTO class_ability(class_id, ability_id) VALUES (5, 13);
INSERT INTO class_ability(class_id, ability_id) VALUES (5, 14);
INSERT INTO class_ability(class_id, ability_id) VALUES (5, 15);
INSERT INTO class_passive(class_id, passive_id) VALUES (5, 9);
INSERT INTO class_passive(class_id, passive_id) VALUES (5, 10);

INSERT INTO class(name, parent_id) VALUES('Shaman', 5);
INSERT INTO class_stat(class_id, stat_id, type_id) VALUES(6, 5, 1);
INSERT INTO class_stat(class_id, stat_id, type_id) VALUES(6, 4, 1);
INSERT INTO class_stat(class_id, stat_id, type_id) VALUES(6, 2, 2);
INSERT INTO class_ability(class_id, ability_id) VALUES (6, 16);
INSERT INTO class_ability(class_id, ability_id) VALUES (6, 17);
INSERT INTO class_ability(class_id, ability_id) VALUES (6, 18);
INSERT INTO class_passive(class_id, passive_id) VALUES (6, 11);
INSERT INTO class_passive(class_id, passive_id) VALUES (6, 12);

INSERT INTO class(name, parent_id) VALUES('Timekeeper', 5);
INSERT INTO class_stat(class_id, stat_id, type_id) VALUES(7, 5, 1);
INSERT INTO class_stat(class_id, stat_id, type_id) VALUES(7, 6, 2);
INSERT INTO class_ability(class_id, ability_id) VALUES (7, 19);
INSERT INTO class_ability(class_id, ability_id) VALUES (7, 20);
INSERT INTO class_ability(class_id, ability_id) VALUES (7, 21);
INSERT INTO class_passive(class_id, passive_id) VALUES (7, 13);
INSERT INTO class_passive(class_id, passive_id) VALUES (7, 14);

INSERT INTO class(name, parent_id) VALUES('Warden', 5);
INSERT INTO class_stat(class_id, stat_id, type_id) VALUES(8, 5, 1);
INSERT INTO class_stat(class_id, stat_id, type_id) VALUES(8, 3, 1);
INSERT INTO class_stat(class_id, stat_id, type_id) VALUES(8, 6, 2);
INSERT INTO class_ability(class_id, ability_id) VALUES (8, 22);
INSERT INTO class_ability(class_id, ability_id) VALUES (8, 23);
INSERT INTO class_ability(class_id, ability_id) VALUES (8, 24);
INSERT INTO class_passive(class_id, passive_id) VALUES (8, 15);
INSERT INTO class_passive(class_id, passive_id) VALUES (8, 16);

INSERT INTO class(name) VALUES('Warlock');
INSERT INTO class_stat(class_id, stat_id, type_id) VALUES(9, 6, 1);
INSERT INTO class_stat(class_id, stat_id, type_id) VALUES(9, 3, 1);
INSERT INTO class_stat(class_id, stat_id, type_id) VALUES(9, 5, 2);
INSERT INTO class_ability(class_id, ability_id) VALUES (9, 25);
INSERT INTO class_ability(class_id, ability_id) VALUES (9, 26);
INSERT INTO class_ability(class_id, ability_id) VALUES (9, 27);
INSERT INTO class_passive(class_id, passive_id) VALUES (9, 17);
INSERT INTO class_passive(class_id, passive_id) VALUES (9, 18);

INSERT INTO class(name, parent_id) VALUES('Witch', 9);
INSERT INTO class_stat(class_id, stat_id, type_id) VALUES(10, 4, 1);
INSERT INTO class_stat(class_id, stat_id, type_id) VALUES(10, 5, 1);
INSERT INTO class_stat(class_id, stat_id, type_id) VALUES(10, 6, 2);
INSERT INTO class_ability(class_id, ability_id) VALUES (10, 28);
INSERT INTO class_ability(class_id, ability_id) VALUES (10, 29);
INSERT INTO class_ability(class_id, ability_id) VALUES (10, 30);
INSERT INTO class_passive(class_id, passive_id) VALUES (10, 19);
INSERT INTO class_passive(class_id, passive_id) VALUES (10, 20);

INSERT INTO class(name, parent_id) VALUES('Summoner', 9);
INSERT INTO class_stat(class_id, stat_id, type_id) VALUES(11, 4, 1);
INSERT INTO class_stat(class_id, stat_id, type_id) VALUES(11, 5, 1);
INSERT INTO class_stat(class_id, stat_id, type_id) VALUES(11, 6, 2);
INSERT INTO class_ability(class_id, ability_id) VALUES (11, 31);
INSERT INTO class_ability(class_id, ability_id) VALUES (11, 32);
INSERT INTO class_ability(class_id, ability_id) VALUES (11, 33);
INSERT INTO class_passive(class_id, passive_id) VALUES (11, 21);
INSERT INTO class_passive(class_id, passive_id) VALUES (11, 22);

INSERT INTO class(name, parent_id) VALUES('Death', 9);
INSERT INTO class_stat(class_id, stat_id, type_id) VALUES(12, 5, 1);
INSERT INTO class_stat(class_id, stat_id, type_id) VALUES(12, 3, 1);
INSERT INTO class_stat(class_id, stat_id, type_id) VALUES(12, 6, 2);
INSERT INTO class_ability(class_id, ability_id) VALUES (12, 34);
INSERT INTO class_ability(class_id, ability_id) VALUES (12, 35);
INSERT INTO class_ability(class_id, ability_id) VALUES (12, 36);
INSERT INTO class_passive(class_id, passive_id) VALUES (12, 23);
INSERT INTO class_passive(class_id, passive_id) VALUES (12, 24);

INSERT INTO class(name) VALUES('Cleric');
INSERT INTO class_stat(class_id, stat_id, type_id) VALUES(13, 6, 1);
INSERT INTO class_stat(class_id, stat_id, type_id) VALUES(13, 5, 1);
INSERT INTO class_stat(class_id, stat_id, type_id) VALUES(13, 2, 2);
INSERT INTO class_ability(class_id, ability_id) VALUES (13, 37); -- leet
INSERT INTO class_ability(class_id, ability_id) VALUES (13, 38);
INSERT INTO class_ability(class_id, ability_id) VALUES (13, 39);
INSERT INTO class_passive(class_id, passive_id) VALUES (13, 25);
INSERT INTO class_passive(class_id, passive_id) VALUES (13, 26);

INSERT INTO class(name, parent_id) VALUES('Diviner', 13);
INSERT INTO class_stat(class_id, stat_id, type_id) VALUES(14, 6, 1);
INSERT INTO class_stat(class_id, stat_id, type_id) VALUES(14, 5, 1);
INSERT INTO class_stat(class_id, stat_id, type_id) VALUES(14, 2, 2);
INSERT INTO class_ability(class_id, ability_id) VALUES (14, 40);
INSERT INTO class_ability(class_id, ability_id) VALUES (14, 41);
INSERT INTO class_ability(class_id, ability_id) VALUES (14, 42);
INSERT INTO class_passive(class_id, passive_id) VALUES (14, 13);
INSERT INTO class_passive(class_id, passive_id) VALUES (14, 27);

INSERT INTO class(name, parent_id) VALUES('Radiance', 13);
INSERT INTO class_stat(class_id, stat_id, type_id) VALUES(15, 4, 1);
INSERT INTO class_stat(class_id, stat_id, type_id) VALUES(15, 6 ,2);
INSERT INTO class_ability(class_id, ability_id) VALUES (15, 43);
INSERT INTO class_ability(class_id, ability_id) VALUES (15, 44);
INSERT INTO class_ability(class_id, ability_id) VALUES (15, 45);
INSERT INTO class_passive(class_id, passive_id) VALUES (15, 28);
INSERT INTO class_passive(class_id, passive_id) VALUES (15, 29);

INSERT INTO class(name, parent_id) VALUES('Cultist', 13);
INSERT INTO class_stat(class_id, stat_id, type_id) VALUES(16, 5, 1);
INSERT INTO class_stat(class_id, stat_id, type_id) VALUES(16, 6, 2);
INSERT INTO class_ability(class_id, ability_id) VALUES (16, 46);
INSERT INTO class_ability(class_id, ability_id) VALUES (16, 47);
INSERT INTO class_ability(class_id, ability_id) VALUES (16, 48);
INSERT INTO class_passive(class_id, passive_id) VALUES (16, 30);
INSERT INTO class_passive(class_id, passive_id) VALUES (16, 31);

INSERT INTO class(name) VALUES('Mage');
INSERT INTO class_stat(class_id, stat_id, type_id) VALUES(17, 4, 1);
INSERT INTO class_stat(class_id, stat_id, type_id) VALUES(17, 5, 1);
INSERT INTO class_stat(class_id, stat_id, type_id) VALUES(17, 6, 2);
INSERT INTO class_stat(class_id, stat_id, type_id) VALUES(17, 2, 2);
INSERT INTO class_ability(class_id, ability_id) VALUES (17, 49);
INSERT INTO class_ability(class_id, ability_id) VALUES (17, 50);
INSERT INTO class_ability(class_id, ability_id) VALUES (17, 51);
INSERT INTO class_passive(class_id, passive_id) VALUES (17, 32);
INSERT INTO class_passive(class_id, passive_id) VALUES (17, 33);

INSERT INTO class(name, parent_id) VALUES('Artificer', 17);
INSERT INTO class_stat(class_id, stat_id, type_id) VALUES(18, 5, 1);
INSERT INTO class_stat(class_id, stat_id, type_id) VALUES(18, 6, 2);
INSERT INTO class_ability(class_id, ability_id) VALUES (18, 52);
INSERT INTO class_ability(class_id, ability_id) VALUES (18, 53);
INSERT INTO class_ability(class_id, ability_id) VALUES (18, 54);
INSERT INTO class_passive(class_id, passive_id) VALUES (18, 34);
INSERT INTO class_passive(class_id, passive_id) VALUES (18, 35);

INSERT INTO class(name, parent_id) VALUES('Wizard', 17);
INSERT INTO class_stat(class_id, stat_id, type_id) VALUES(19, 4, 1);
INSERT INTO class_stat(class_id, stat_id, type_id) VALUES(19, 5, 2);
INSERT INTO class_ability(class_id, ability_id) VALUES (19, 55);
INSERT INTO class_ability(class_id, ability_id) VALUES (19, 56);
INSERT INTO class_ability(class_id, ability_id) VALUES (19, 57);
INSERT INTO class_passive(class_id, passive_id) VALUES (19, 36);
INSERT INTO class_passive(class_id, passive_id) VALUES (19, 37);

INSERT INTO class(name, parent_id) VALUES('Sorcerer', 17);
INSERT INTO class_stat(class_id, stat_id, type_id) VALUES(20, 4, 1);
INSERT INTO class_stat(class_id, stat_id, type_id) VALUES(20, 5, 1);
INSERT INTO class_stat(class_id, stat_id, type_id) VALUES(20, 2, 2);
INSERT INTO class_ability(class_id, ability_id) VALUES (20, 58);
INSERT INTO class_ability(class_id, ability_id) VALUES (20, 59);
INSERT INTO class_ability(class_id, ability_id) VALUES (20, 60);
INSERT INTO class_passive(class_id, passive_id) VALUES (20, 38);
INSERT INTO class_passive(class_id, passive_id) VALUES (20, 39);

INSERT INTO class(name) VALUES('Ranger');
INSERT INTO class_stat(class_id, stat_id, type_id) VALUES(21, 2, 1);
INSERT INTO class_stat(class_id, stat_id, type_id) VALUES(21, 1, 2);
INSERT INTO class_ability(class_id, ability_id) VALUES (21, 61);
INSERT INTO class_ability(class_id, ability_id) VALUES (21, 62);
INSERT INTO class_ability(class_id, ability_id) VALUES (21, 63);
INSERT INTO class_passive(class_id, passive_id) VALUES (21, 40);
INSERT INTO class_passive(class_id, passive_id) VALUES (21, 41);

INSERT INTO class(name, parent_id) VALUES('Gunslinger', 21);
INSERT INTO class_stat(class_id, stat_id, type_id) VALUES(22, 1, 1);
INSERT INTO class_stat(class_id, stat_id, type_id) VALUES(22, 5, 2);
INSERT INTO class_ability(class_id, ability_id) VALUES (22, 64);
INSERT INTO class_ability(class_id, ability_id) VALUES (22, 65);
INSERT INTO class_ability(class_id, ability_id) VALUES (22, 66);
INSERT INTO class_passive(class_id, passive_id) VALUES (22, 42);
INSERT INTO class_passive(class_id, passive_id) VALUES (22, 43);

INSERT INTO class(name, parent_id) VALUES('Wild Card', 21);
INSERT INTO class_stat(class_id, stat_id, type_id) VALUES(23, 2, 1);
INSERT INTO class_stat(class_id, stat_id, type_id) VALUES(23, 5, 1);
INSERT INTO class_stat(class_id, stat_id, type_id) VALUES(23, 1, 2);
INSERT INTO class_stat(class_id, stat_id, type_id) VALUES(23, 4, 2);
INSERT INTO class_ability(class_id, ability_id) VALUES (23, 67);
INSERT INTO class_ability(class_id, ability_id) VALUES (23, 68);
INSERT INTO class_ability(class_id, ability_id) VALUES (23, 69);
INSERT INTO class_passive(class_id, passive_id) VALUES (23, 44);
INSERT INTO class_passive(class_id, passive_id) VALUES (23, 45);

INSERT INTO class(name) VALUES('Hunter');
INSERT INTO class_stat(class_id, stat_id, type_id) VALUES(24, 2, 1);
INSERT INTO class_stat(class_id, stat_id, type_id) VALUES(24, 1, 1);
INSERT INTO class_stat(class_id, stat_id, type_id) VALUES(24, 6, 2);
INSERT INTO class_ability(class_id, ability_id) VALUES (24, 70);
INSERT INTO class_ability(class_id, ability_id) VALUES (24, 71);
INSERT INTO class_ability(class_id, ability_id) VALUES (24, 72);
INSERT INTO class_passive(class_id, passive_id) VALUES (24, 46);
INSERT INTO class_passive(class_id, passive_id) VALUES (24, 47);

INSERT INTO class(name, parent_id) VALUES('Rogue', 24);
INSERT INTO class_stat(class_id, stat_id, type_id) VALUES(25, 2, 1);
INSERT INTO class_stat(class_id, stat_id, type_id) VALUES(25, 1, 2);
INSERT INTO class_ability(class_id, ability_id) VALUES (25, 73);
INSERT INTO class_ability(class_id, ability_id) VALUES (25, 74);
INSERT INTO class_ability(class_id, ability_id) VALUES (25, 75);
INSERT INTO class_passive(class_id, passive_id) VALUES (25, 48);
INSERT INTO class_passive(class_id, passive_id) VALUES (25, 49);

INSERT INTO class(name, parent_id) VALUES('Nightmare', 24);
INSERT INTO class_stat(class_id, stat_id, type_id) VALUES(26, 2, 1);
INSERT INTO class_stat(class_id, stat_id, type_id) VALUES(26, 5, 1);
INSERT INTO class_stat(class_id, stat_id, type_id) VALUES(26, 1, 2);
INSERT INTO class_ability(class_id, ability_id) VALUES (26, 76);
INSERT INTO class_ability(class_id, ability_id) VALUES (26, 77);
INSERT INTO class_ability(class_id, ability_id) VALUES (26, 78);
INSERT INTO class_passive(class_id, passive_id) VALUES (26, 50);
INSERT INTO class_passive(class_id, passive_id) VALUES (26, 51);

INSERT INTO class(name, parent_id) VALUES('Tricker', 24);
INSERT INTO class_stat(class_id, stat_id, type_id) VALUES(27, 2, 1);
INSERT INTO class_stat(class_id, stat_id, type_id) VALUES(27, 6, 1);
INSERT INTO class_stat(class_id, stat_id, type_id) VALUES(27, 5, 2);
INSERT INTO class_ability(class_id, ability_id) VALUES (27, 79);
INSERT INTO class_ability(class_id, ability_id) VALUES (27, 80);
INSERT INTO class_ability(class_id, ability_id) VALUES (27, 81);
INSERT INTO class_passive(class_id, passive_id) VALUES (27, 52);
INSERT INTO class_passive(class_id, passive_id) VALUES (27, 53);

INSERT INTO class(name) VALUES('Bard');
INSERT INTO class_stat(class_id, stat_id, type_id) VALUES(28, 6, 1);
INSERT INTO class_stat(class_id, stat_id, type_id) VALUES(28, 2, 1);
INSERT INTO class_stat(class_id, stat_id, type_id) VALUES(28, 5, 2);
INSERT INTO class_ability(class_id, ability_id) VALUES (28, 82);
INSERT INTO class_ability(class_id, ability_id) VALUES (28, 83);
INSERT INTO class_ability(class_id, ability_id) VALUES (28, 84);
INSERT INTO class_passive(class_id, passive_id) VALUES (28, 54);
INSERT INTO class_passive(class_id, passive_id) VALUES (28, 55);

INSERT INTO class(name, parent_id) VALUES('Tamer', 28);
INSERT INTO class_stat(class_id, stat_id, type_id) VALUES(29, 6, 1);
INSERT INTO class_stat(class_id, stat_id, type_id) VALUES(29, 5, 1);
INSERT INTO class_stat(class_id, stat_id, type_id) VALUES(29, 2, 2);
INSERT INTO class_ability(class_id, ability_id) VALUES (29, 85);
INSERT INTO class_ability(class_id, ability_id) VALUES (29, 86);
INSERT INTO class_ability(class_id, ability_id) VALUES (29, 87);
INSERT INTO class_passive(class_id, passive_id) VALUES (29, 56);
INSERT INTO class_passive(class_id, passive_id) VALUES (29, 57);

INSERT INTO class(name, parent_id) VALUES('Puppeteer', 28);
INSERT INTO class_stat(class_id, stat_id, type_id) VALUES(30, 6, 1);
INSERT INTO class_stat(class_id, stat_id, type_id) VALUES(30, 5, 1);
INSERT INTO class_stat(class_id, stat_id, type_id) VALUES(30, 2, 2);
INSERT INTO class_ability(class_id, ability_id) VALUES (30, 88);
INSERT INTO class_ability(class_id, ability_id) VALUES (30, 89);
INSERT INTO class_ability(class_id, ability_id) VALUES (30, 90);
INSERT INTO class_passive(class_id, passive_id) VALUES (30, 58);
INSERT INTO class_passive(class_id, passive_id) VALUES (30, 59);

INSERT INTO class(name, parent_id) VALUES('Performer', 28);
INSERT INTO class_stat(class_id, stat_id, type_id) VALUES(31, 5, 1);
INSERT INTO class_stat(class_id, stat_id, type_id) VALUES(31, 6, 1);
INSERT INTO class_stat(class_id, stat_id, type_id) VALUES(31, 4, 2);
INSERT INTO class_ability(class_id, ability_id) VALUES (31, 91);
INSERT INTO class_ability(class_id, ability_id) VALUES (31, 92);
INSERT INTO class_ability(class_id, ability_id) VALUES (31, 93);
INSERT INTO class_passive(class_id, passive_id) VALUES (31, 60);
INSERT INTO class_passive(class_id, passive_id) VALUES (31, 61);

INSERT INTO class(name) VALUES('Fighter');
INSERT INTO class_stat(class_id, stat_id, type_id) VALUES(32, 1, 1);
INSERT INTO class_stat(class_id, stat_id, type_id) VALUES(32, 3, 2);
INSERT INTO class_ability(class_id, ability_id) VALUES (32, 94);
INSERT INTO class_ability(class_id, ability_id) VALUES (32, 95);
INSERT INTO class_ability(class_id, ability_id) VALUES (32, 96);
INSERT INTO class_passive(class_id, passive_id) VALUES (32, 62);
INSERT INTO class_passive(class_id, passive_id) VALUES (32, 63);

INSERT INTO class(name, parent_id) VALUES('Pugilist', 32);
INSERT INTO class_stat(class_id, stat_id, type_id) VALUES(33, 1, 1);
INSERT INTO class_stat(class_id, stat_id, type_id) VALUES(33, 2, 2);
INSERT INTO class_ability(class_id, ability_id) VALUES (33, 97);
INSERT INTO class_ability(class_id, ability_id) VALUES (33, 98);
INSERT INTO class_ability(class_id, ability_id) VALUES (33, 99);
INSERT INTO class_passive(class_id, passive_id) VALUES (33, 64);
INSERT INTO class_passive(class_id, passive_id) VALUES (33, 65);

INSERT INTO class(name, parent_id) VALUES('Monk', 32);
INSERT INTO class_stat(class_id, stat_id, type_id) VALUES(34, 5, 1);
INSERT INTO class_stat(class_id, stat_id, type_id) VALUES(34, 3, 2);
INSERT INTO class_ability(class_id, ability_id) VALUES (34, 100);
INSERT INTO class_ability(class_id, ability_id) VALUES (34, 101);
INSERT INTO class_ability(class_id, ability_id) VALUES (34, 102);
INSERT INTO class_passive(class_id, passive_id) VALUES (34, 66);
INSERT INTO class_passive(class_id, passive_id) VALUES (34, 67);

INSERT INTO class(name, parent_id) VALUES('Captain', 32);
INSERT INTO class_stat(class_id, stat_id, type_id) VALUES(35, 1, 1);
INSERT INTO class_stat(class_id, stat_id, type_id) VALUES(35, 2, 2);
INSERT INTO class_ability(class_id, ability_id) VALUES (35, 103);
INSERT INTO class_ability(class_id, ability_id) VALUES (35, 104);
INSERT INTO class_ability(class_id, ability_id) VALUES (35, 105);
INSERT INTO class_passive(class_id, passive_id) VALUES (35, 68);
INSERT INTO class_passive(class_id, passive_id) VALUES (35, 69);

INSERT INTO class(name) VALUES('Knight');
INSERT INTO class_stat(class_id, stat_id, type_id) VALUES(36, 3, 1);
INSERT INTO class_stat(class_id, stat_id, type_id) VALUES(36, 1, 2);
INSERT INTO class_ability(class_id, ability_id) VALUES (36, 106);
INSERT INTO class_ability(class_id, ability_id) VALUES (36, 107);
INSERT INTO class_ability(class_id, ability_id) VALUES (36, 108);
INSERT INTO class_passive(class_id, passive_id) VALUES (36, 70);
INSERT INTO class_passive(class_id, passive_id) VALUES (36, 71);

INSERT INTO class(name, parent_id) VALUES('Paladin', 36);
INSERT INTO class_stat(class_id, stat_id, type_id) VALUES(37, 6, 1);
INSERT INTO class_stat(class_id, stat_id, type_id) VALUES(37, 3, 1);
INSERT INTO class_stat(class_id, stat_id, type_id) VALUES(37, 1, 2);
INSERT INTO class_ability(class_id, ability_id) VALUES (37, 109);
INSERT INTO class_ability(class_id, ability_id) VALUES (37, 110);
INSERT INTO class_ability(class_id, ability_id) VALUES (37, 111);
INSERT INTO class_passive(class_id, passive_id) VALUES (37, 72);
INSERT INTO class_passive(class_id, passive_id) VALUES (37, 73);

INSERT INTO class(name, parent_id) VALUES('King', 36);
INSERT INTO class_stat(class_id, stat_id, type_id) VALUES(38, 3, 1);
INSERT INTO class_stat(class_id, stat_id, type_id) VALUES(38, 1, 1);
INSERT INTO class_stat(class_id, stat_id, type_id) VALUES(38, 6, 2);
INSERT INTO class_ability(class_id, ability_id) VALUES (38, 112);
INSERT INTO class_ability(class_id, ability_id) VALUES (38, 113);
INSERT INTO class_ability(class_id, ability_id) VALUES (38, 114);
INSERT INTO class_passive(class_id, passive_id) VALUES (38, 74);
INSERT INTO class_passive(class_id, passive_id) VALUES (38, 75);

INSERT INTO class(name, parent_id) VALUES('Blade Dancer', 36);
INSERT INTO class_stat(class_id, stat_id, type_id) VALUES(39, 2, 1);
INSERT INTO class_stat(class_id, stat_id, type_id) VALUES(39, 5, 1);
INSERT INTO class_stat(class_id, stat_id, type_id) VALUES(39, 1, 2);
INSERT INTO class_ability(class_id, ability_id) VALUES (39, 115);
INSERT INTO class_ability(class_id, ability_id) VALUES (39, 116);
INSERT INTO class_ability(class_id, ability_id) VALUES (39, 117);
INSERT INTO class_passive(class_id, passive_id) VALUES (39, 76);
INSERT INTO class_passive(class_id, passive_id) VALUES (39, 77);

INSERT INTO class(name) VALUES('Scholar');
INSERT INTO class_stat(class_id, stat_id, type_id) VALUES(40, 5, 1);
INSERT INTO class_stat(class_id, stat_id, type_id) VALUES(40, 6, 2);
INSERT INTO class_ability(class_id, ability_id) VALUES (40, 118);
INSERT INTO class_ability(class_id, ability_id) VALUES (40, 119);
INSERT INTO class_ability(class_id, ability_id) VALUES (40, 120);
INSERT INTO class_passive(class_id, passive_id) VALUES (40, 78);
INSERT INTO class_passive(class_id, passive_id) VALUES (40, 79);

INSERT INTO class(name, parent_id) VALUES('Doorman', 40);
INSERT INTO class_stat(class_id, stat_id, type_id) VALUES(41, 3, 1);
INSERT INTO class_stat(class_id, stat_id, type_id) VALUES(41, 5, 2);
INSERT INTO class_ability(class_id, ability_id) VALUES (41, 121);
INSERT INTO class_ability(class_id, ability_id) VALUES (41, 122);
INSERT INTO class_ability(class_id, ability_id) VALUES (41, 123);
INSERT INTO class_passive(class_id, passive_id) VALUES (41, 80);
INSERT INTO class_passive(class_id, passive_id) VALUES (41, 81);

INSERT INTO class(name, parent_id) VALUES('Janitor', 40);
INSERT INTO class_stat(class_id, stat_id, type_id) VALUES(42, 5, 1);
INSERT INTO class_stat(class_id, stat_id, type_id) VALUES(42, 6, 2);
INSERT INTO class_ability(class_id, ability_id) VALUES (42, 124);
INSERT INTO class_ability(class_id, ability_id) VALUES (42, 125);
INSERT INTO class_ability(class_id, ability_id) VALUES (42, 126);
INSERT INTO class_passive(class_id, passive_id) VALUES (42, 82);
INSERT INTO class_passive(class_id, passive_id) VALUES (42, 83);

INSERT INTO class(name, parent_id) VALUES('Messenger', 40);
INSERT INTO class_stat(class_id, stat_id, type_id) VALUES(43, 5, 1);
INSERT INTO class_stat(class_id, stat_id, type_id) VALUES(43, 6, 2);
INSERT INTO class_ability(class_id, ability_id) VALUES (43, 127);
INSERT INTO class_ability(class_id, ability_id) VALUES (43, 128);
INSERT INTO class_ability(class_id, ability_id) VALUES (43, 129);
INSERT INTO class_passive(class_id, passive_id) VALUES (43, 84);
INSERT INTO class_passive(class_id, passive_id) VALUES (43, 85);