[project]
name = "sumi-dnd"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Tristan Bonaobra", email = "316808543+tristan-bonaobra@users.noreply.github.com" }
]
requires-python = ">=3.14"
dependencies = [
    "dotenv>=0.9.9",
    "pandas>=3.0.5",
    "pdfplumber>=0.11.10",
    "sqlalchemy>=2.0.52",
    "tabulate>=0.10.0",
]

[project.scripts]
sumi-dnd = "sumi_dnd:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "deptry>=0.25.1",
]

[tool.deptry]
known_first_party = ["sumi_dnd"]